pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: true
        script:
          - git clone --bare git@bitbucket.org/temporaryjobs/lh_hrm.git
          - cd tempojobs.git
          - git push --mirror git@github.com:johnH872/HRM.git